
engines:

  eslint:
    enabled: true
    config:
      extensions:
      - .js
    ratings:
      paths:
      - src/**
      - project_react/**
      - "**.js"

  duplication:
    enabled: true
    config:
      languages:
        - javascript
