
engines:

  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
    config:
      extensions:
      - .js
    ratings:
      paths:
      - src/**
      - "**.js"

  duplication:
    enabled: false
    config:
      languages:
        - javascript
