
engines:

  eslint:
    enabled: true
    checks:
      complexity:
        enabled: true
    config:
      extensions:
      - .js

  duplication:
    enabled: true
    config:
      languages:
        - javascript

ratings:
  paths:
  - "**.js"
